// dailyTips.js
// Contains daily tips for Cortex Task Manager. You can add more tips as needed.

const dailyTips = [
  "Plan Your Day the Night Before: Create a to-do list for the next day to hit the ground running.",
  "Identify Your Top 3 Priorities: Each day, decide on the three most important tasks and tackle them first.",
  "Use the Pomodoro Technique: Work for 25 minutes, then take a 5-minute break. Repeat.",
  "Eat the Frog: Start your day with the most challenging task you're dreading.",
  "Timebox Your Tasks: Allocate a specific time slot for each task on your calendar.",
  "Declutter Your Workspace: A clean space leads to a clear mind and better focus.",
  "Turn Off Notifications: Minimize distractions from your phone and computer.",
  "Set a Timer for Social Media: If you must browse, limit it to a specific, short period.",
  "Learn to Say No: Politely decline requests that don't align with your priorities.",
  "Batch Similar Tasks: Group similar activities (like answering emails) and do them all at once.",
  "Use a Planner or App: Keep track of deadlines, appointments, and tasks in one place.",
  "Review Your Week: Every Friday, review what you accomplished and plan for the week ahead.",
  "Delegate When Possible: Don't be afraid to ask for help or assign tasks to others.",
  "Take Regular Breaks: Step away from your work to recharge your mind.",
  "Avoid Multitasking: Focus on one thing at a time for higher quality results.",
  "Set Deadlines for Everything: Even for small tasks, a deadline creates a sense of urgency.",
  "Define Your \"Why\": Remind yourself of the larger goals behind your daily tasks.",
  "Break Down Large Goals: Divide big projects into smaller, manageable steps.",
  "Celebrate Small Wins: Acknowledge and reward yourself for making progress.",
  "Visualize Success: Spend a few minutes each morning picturing yourself achieving your goals.",
  "Create a Motivational Playlist: Listen to music that energizes and inspires you.",
  "Read or Listen to Something Inspiring: Start your day with a positive book, podcast, or article.",
  "Track Your Progress: Keep a journal or use an app to see how far you've come.",
  "Find an Accountability Partner: Share your goals with someone who can help you stay on track.",
  "Remember Past Successes: When feeling discouraged, think back on challenges you've already overcome.",
  "Surround Yourself with Positive People: Limit time with negative individuals who drain your energy.",
  "Just Start for 5 Minutes: When you don't feel like working, commit to just five minutes. You'll often keep going.",
  "Reward Yourself After a Hard Task: Plan something enjoyable to do after you complete a difficult task.",
  "Get Dressed for Success: Even if you work from home, dressing the part can boost your mindset.",
  "Set a Routine: A consistent daily routine can build momentum and reduce the need for constant motivation.",
  "Learn Something New: Continuously learning can keep you engaged and excited.",
  "Focus on the Journey, Not Just the Destination: Find joy in the process of working toward your goals.",
  "Practice Positive Affirmations: Start your day by saying positive statements about yourself.",
  "Challenge Negative Self-Talk: When a negative thought arises, question its validity and reframe it.",
  "Accomplish a Small Goal: Checking something off your list, no matter how small, builds confidence.",
  "Exercise Regularly: Physical activity is a proven mood and confidence booster.",
  "Practice Good Posture: Stand up straight, pull your shoulders back, and hold your head high.",
  "Dress in a Way That Makes You Feel Good: Wear clothes that make you feel comfortable and confident.",
  "Step Outside Your Comfort Zone: Try something new and prove to yourself that you can handle it.",
  "Prepare and Practice: Feel more confident by being well-prepared for presentations, meetings, or events.",
  "Focus on Your Strengths: Regularly remind yourself of what you're good at.",
  "Accept Compliments Gracefully: Simply say \"Thank you\" instead of downplaying the praise.",
  "Practice Gratitude: Each day, write down three things you are grateful for.",
  "Help Someone Else: Being of service to others can boost your sense of self-worth.",
  "Set Healthy Boundaries: Learn to protect your time and energy.",
  "Speak Slowly and Clearly: This projects confidence and authority.",
  "Make Eye Contact: When talking to others, maintain comfortable eye contact.",
  "Stop Comparing Yourself to Others: Focus on your own journey and progress.",
  "Embrace Imperfection: Understand that it's okay not to be perfect. Strive for progress, not perfection.",
  "Forgive Yourself for Mistakes: Treat yourself with the same kindness you would offer a friend."
];


export default dailyTips;
